[tool.poetry]
name = "netbox-plugin-prometheus-sd"
version = "0.0.0" # placeholder
description = "A Netbox plugin to provide Netbox entires to Prometheus HTTP service discovery"
authors = ["Felix Peters <felix.peters@breuninger.de>"]
license = "MIT"
readme = "README.md"

packages = [
    { include = "netbox_prometheus_sd" },
]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
black = "^21.12b0"
invoke = "^1.6.0"
pylint = "^2.12.1"
pylint-django = "^2.4.4"
yamllint = "^1.26.2"
typed-ast = "^1.5.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
