[tool.poetry]
name = "netbox-plugin-prometheus-sd"
version = "0.1.0"
description = "A Netbox plugin to provide Netbox entires to Prometheus HTTP service discovery"
authors = ["Felix Peters <felix.peters@breuninger.de>"]
license = "MIT"

packages = [
    { include = "netbox_prometheus_sd" },
]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
bandit = "^1.7.0"
black = "^21.7b0"
invoke = "^1.6.0"
pylint = "^2.9.6"
pylint-django = "^2.4.4"
pydocstyle = "^6.1.1"
yamllint = "^1.26.3"
typed-ast = "^1.4.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
